apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: sa-reader
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-reader
  namespace: roboshop
subjects:
  - kind: ServiceAccount
    name: roboshop-mysql-secret-reader
    namespace: roboshop
roleRef:
  kind: Role
  name: sa-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  namespace: roboshop
  labels:
    purpose: sa
spec:
  serviceAccount: roboshop-mysql-secret-reader
  containers:
    - name: awscli
      image: amazon/aws-cli
      command: ["sleep", "10000"]
